"""GraphQL client: distill a schema once, then build schema-checked queries by attribute chaining, batched into single requests

A GraphQL API is one endpoint that accepts a *shape*: describe the nesting you want and the server returns exactly that, in one round trip. The price is that you must know the schema to write the shape. This module closes that gap for any GraphQL endpoint: `GqlSpec` distills the standard introspection answer into compact tables a client package can ship, and `GqlClient` uses them to expose the schema for discovery (`xdir`, attribute completion, rich reprs), build queries by attribute chaining with plain-kwargs arguments, and execute many independent queries as one batched request. Raw GraphQL text works at every level, and only query fields are exposed as attributes -- mutations require deliberately writing raw text. Everything except execution is offline: distilling, discovery, and query building need no network.

`GqlClient` executes queries, riding the same `AsyncTransport` as `OpenAPIClient` -- one place for timeouts, header merging, and HTTP errors enriched with the response body. Calling it with raw GraphQL text (plus optional variables) is the whole API in one line; the fragment layer below builds that text for you. GraphQL reports failures as an `errors` list that can arrive *alongside* partial data on a successful HTTP exchange, so failures raise `GqlError`, which keeps the structured list (`.errors`) and any partial payload (`.data`).

Queries are built as *fragments*: attribute access on the client starts a path at a query field, each further attribute extends it a field at a time, and calling a fragment binds arguments as plain kwargs. The seam rule: **args are kwargs; selection is attribute chaining when linear, raw GraphQL text when not.** Argument values render as GraphQL literals -- strings quoted, enums (recognized from the schema, including inside input objects) bare:

Because a query is a shape, "run these N fragments" is just one bigger shape: `batch` aliases each fragment into a single request and returns results in input order, with `None` for any alias that errored rather than killing the other answers:

Docs: https://AnswerDotAI.github.io/fastspec/gql.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_gql.ipynb.

# %% auto #0
__all__ = ['INTROSPECT', 'distill', 'GqlSpec', 'GqlError', 'GqlClient', 'GqlFrag']

# %% ../nbs/05_gql.ipynb #afa6b7a9
from fastcore.utils import *
from .transport import AsyncTransport

import json

# %% ../nbs/05_gql.ipynb #ebe078a2
_TREF = 'kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name } } } }'
INTROSPECT = '''{
  __schema {
    queryType { name } mutationType { name }
    types {
      kind name description
      fields(includeDeprecated: false) {
        name description
        args { name description defaultValue type { %s } }
        type { %s }
      }
      inputFields { name description defaultValue type { %s } }
      enumValues { name description }
      possibleTypes { name }
    }
  }
}''' % (_TREF, _TREF, _TREF)

def _tstr(t):
    "Render an introspection type ref as GraphQL notation, e.g. '[Ref!]!'"
    if t['kind'] == 'NON_NULL': return _tstr(t['ofType']) + '!'
    if t['kind'] == 'LIST': return '[' + _tstr(t['ofType']) + ']'
    return t['name']

def _desc(s): return s.strip().split('\n', 1)[0].strip() if s else ''

# %% ../nbs/05_gql.ipynb #770df512
def _fieldrec(f):
    "Compact record for one object field: rendered type, first-line doc, and per-arg [type, doc, default]"
    return dict(type=_tstr(f['type']), desc=_desc(f['description']),
        args={a['name']: [_tstr(a['type']), _desc(a['description']), a['defaultValue']] for a in f['args']})

def distill(raw):
    "Distill standard introspection JSON into compact lookup tables"
    sch = raw['data']['__schema']
    types = {}
    for t in sch['types']:
        nm = t['name']
        if nm.startswith('__'): continue
        d = dict(kind=t['kind'])
        if _desc(t['description']): d['desc'] = _desc(t['description'])
        if t['kind'] in ('OBJECT', 'INTERFACE'): d['fields'] = {f['name']: _fieldrec(f) for f in t['fields'] or []}
        elif t['kind'] == 'INPUT_OBJECT':
            d['fields'] = {f['name']: dict(type=_tstr(f['type']), desc=_desc(f['description']), default=f['defaultValue'])
                for f in t['inputFields'] or []}
        elif t['kind'] == 'ENUM': d['values'] = {v['name']: _desc(v['description']) for v in t['enumValues'] or []}
        elif t['kind'] == 'UNION': d['of'] = [p['name'] for p in t['possibleTypes'] or []]
        types[nm] = d
    return dict(query=sch['queryType']['name'], mutation=sch['mutationType']['name'], types=types)

# %% ../nbs/05_gql.ipynb #8e231452
class GqlSpec:
    "Distilled GraphQL schema: field/arg/type lookup tables, shippable via `save`"
    def __init__(self, query, mutation, types): self.query, self.mutation, self.types = query, mutation, types

    @classmethod
    def from_introspection(cls, raw):
        "Build from a standard introspection answer (see `INTROSPECT`)"
        return cls(**distill(raw))

    @classmethod
    def from_dict(cls, d): return cls(**d)
    def to_dict(self): return dict(query=self.query, mutation=self.mutation, types=self.types)

    def save(self, nm):
        "Write an importable module exposing these tables as `gqlspec`, one line per type"
        lines = [f'gqlspec = {{"query": {self.query!r}, "mutation": {self.mutation!r}, "types": {{']
        lines += [f'{k!r}: {v!r},' for k, v in self.types.items()]
        Path(nm).write_text('\n'.join(lines + ['}}']))

    @property
    def t(self): return _TypeIdx(self.types)

    def __repr__(self): return f'GqlSpec(query={self.query!r}, types={len(self.types)})'

# %% ../nbs/05_gql.ipynb #7d53ed64
class _TypeInfo:
    def __init__(self, types, nm): self._types, self._nm = types, nm
    def __dir__(self): return list(self._types[self._nm].get('fields', {}))
    def __repr__(self):
        t = self._types[self._nm]
        res = [f'{self._nm} ({t["kind"]})'] + ([t['desc']] if t.get('desc') else [])
        if t['kind'] == 'ENUM': res += [f'  {k}: {v}' if v else f'  {k}' for k, v in t['values'].items()]
        elif t['kind'] == 'UNION': res.append('one of: ' + ', '.join(t['of']))
        else: res += [f'  {k}: {f["type"]}' + (f'  # {f["desc"]}' if f['desc'] else '') for k, f in t.get('fields', {}).items()]
        return '\n'.join(res)

class _TypeIdx:
    def __init__(self, types): self._types = types
    def __dir__(self): return list(self._types)
    def __getattr__(self, k):
        if k.startswith('_') or k not in self._types: raise AttributeError(k)
        return _TypeInfo(self._types, k)

# %% ../nbs/05_gql.ipynb #39ef587d
class GqlError(Exception):
    "A GraphQL `errors` response; `errors` is the structured list, `data` any partial payload"
    def __init__(self, errors, data=None):
        self.errors, self.data = errors, data
        super().__init__('; '.join(e.get('message', str(e)) for e in errors))

class GqlClient:
    "GraphQL client over a `GqlSpec`: query fields as attributes, `batch` for one-request fan-out"
    def __init__(self, spec, url, *, headers=None, timeout=60.0):
        self.spec, self.url = spec, url
        self.transport = AsyncTransport(timeout=timeout, base_headers=headers)

    async def _post(self, query, **vars):
        return await self.transport.request('POST', self.url, json_data=dict(query=query, variables=vars or None))

    async def __call__(self, query, **vars):
        res = await self._post(query, **vars)
        if res.get('errors'): raise GqlError(res['errors'], res.get('data'))
        return dict2obj(res['data'])

    def __getattr__(self, k):
        if k.startswith('_') or k in ('spec', 'url', 'transport'): raise AttributeError(k)
        if k not in self.spec.types[self.spec.query]['fields']: raise AttributeError(f'no query field {k!r}')
        return GqlFrag(self, ((k, {}, None),))

    def __dir__(self): return list(self.spec.types[self.spec.query]['fields'])

    @property
    def t(self): return self.spec.t

# %% ../nbs/05_gql.ipynb #78a32abe
def _basetype(tstr): return re.sub(r'[\[\]!]', '', tstr)

def _fmt_val(v, tstr, types):
    "Python value -> GraphQL literal; enum strings and input-object fields typed per the schema"
    base = types.get(_basetype(tstr), {})
    if isinstance(v, str) and base.get('kind') == 'ENUM': return v
    if isinstance(v, bool): return 'true' if v else 'false'
    if v is None: return 'null'
    if isinstance(v, (int, float)): return str(v)
    if isinstance(v, str): return json.dumps(v)
    if isinstance(v, (list, tuple)): return '[' + ', '.join(_fmt_val(o, tstr, types) for o in v) + ']'
    if isinstance(v, dict):
        flds = base.get('fields', {})
        return '{' + ', '.join(f'{k}: {_fmt_val(o, flds.get(k, {}).get("type", ""), types)}' for k, o in v.items()) + '}'
    raise TypeError(f'Cannot render {type(v)} as GraphQL literal')

def _fmt_args(args, argspec, types):
    if not args: return ''
    return '(' + ', '.join(f'{k}: {_fmt_val(v, argspec.get(k, [""])[0], types)}' for k, v in args.items()) + ')'

# %% ../nbs/05_gql.ipynb #c37d4669
class GqlFrag:
    "A lazily-built GraphQL query path: attribute access extends it, calling binds args, awaiting executes"
    def __init__(self, client, steps): self._c, self._steps = client, steps

    def _fieldinfo(self, i=None):
        "The (result type name, field spec) at step `i` (default last), walking from the query root"
        types = self._c.spec.types
        cur, fs = self._c.spec.query, None
        for nm, _, _ in (self._steps if i is None else self._steps[:i+1]):
            fs = types[cur]['fields'][nm]
            cur = _basetype(fs['type'])
        return cur, fs

    def _curtype(self): return self._fieldinfo()[0]
    def _isleaf(self):
        t = self._c.spec.types.get(self._curtype())
        return t is None or t['kind'] in ('SCALAR', 'ENUM')

    def __getattr__(self, k):
        if k.startswith('_'): raise AttributeError(k)
        if self._steps[-1][2] is not None: raise AttributeError('cannot chain past a raw selection')
        flds = self._c.spec.types[self._curtype()].get('fields', {})
        if k not in flds: raise AttributeError(f'{self._curtype()} has no field {k!r}; xdir this fragment to list fields')
        return GqlFrag(self._c, self._steps + ((k, {}, None),))

    def __call__(self, raw=None, **kw):
        nm, args, _ = self._steps[-1]
        return GqlFrag(self._c, self._steps[:-1] + ((nm, {**args, **kw}, raw),))

    def __dir__(self): return list(self._c.spec.types[self._curtype()].get('fields', {}))

# %% ../nbs/05_gql.ipynb #60ecbb53
@patch
def _qbody(self:GqlFrag):
    types, out = self._c.spec.types, ''
    for i in range(len(self._steps) - 1, -1, -1):
        nm, args, raw = self._steps[i]
        s = nm + _fmt_args(args, self._fieldinfo(i)[1]['args'], types)
        if raw: s += ' { ' + raw + ' }'
        elif out: s += ' { ' + out + ' }'
        out = s
    return out

@patch
def _q(self:GqlFrag): return '{ ' + self._qbody() + ' }'

# %% ../nbs/05_gql.ipynb #e72795c1
@patch
def __repr__(self:GqlFrag):
    if self._isleaf() or self._steps[-1][2] is not None: return self._q()
    cur, fs = self._fieldinfo()
    nm = self._steps[-1][0]
    args = ', '.join(f'{k}: {v[0]}' + (f' = {v[2]}' if v[2] is not None else '') for k, v in fs['args'].items())
    res = [f'{nm}({args}) -> {fs["type"]}' if args else f'{nm} -> {fs["type"]}']
    if fs['desc']: res.append(fs['desc'])
    if argdocs := [f'  {k}: {v[1]}' for k, v in fs['args'].items() if v[1]]: res += ['args:'] + argdocs
    if flds := self._c.spec.types[cur].get('fields', {}):
        res.append(f'fields of {cur}: ' + ' '.join(list(flds)[:20]) + (' ...' if len(flds) > 20 else ''))
    return '\n'.join(res)

# %% ../nbs/05_gql.ipynb #9c52696f
def _unwrap(data, steps):
    for nm, _, raw in steps:
        if data is None: return None
        data = data[nm]
        if raw: break
    return data

@patch
def __await__(self:GqlFrag):
    async def _go():
        if not self._isleaf() and self._steps[-1][2] is None:
            raise TypeError(f'{self._curtype()} needs a selection: chain to a leaf field, or call with raw GraphQL text')
        return _unwrap(await self._c(self._q()), self._steps)
    return _go().__await__()

# %% ../nbs/05_gql.ipynb #148d07d4
@patch
async def batch(self:GqlClient, *frags):
    "Execute fragments as one aliased request; results in input order, `None` where an alias errored (e.g. a missing item)"
    res = await self._post('{ ' + ' '.join(f'r{i}: {f._qbody()}' for i, f in enumerate(frags)) + ' }')
    if res.get('data') is None or any(not e.get('path') for e in res.get('errors', [])):
        raise GqlError(res.get('errors', [dict(message='no data')]), res.get('data'))
    data = dict2obj(res['data'])
    return [None if data[f'r{i}'] is None else _unwrap({f._steps[0][0]: data[f'r{i}']}, f._steps) for i, f in enumerate(frags)]
