"""Dynamic OpenAPI operation client: async by default, sync on request.

Docs: https://AnswerDotAI.github.io/fastspec/oapi.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_oapi.ipynb.

# %% auto #0
__all__ = ['OpFunc', 'op_func', 'SyncOpFunc', 'OpenAPIClient']

# %% ../nbs/04_oapi.ipynb #632a2010
import httpx2,json,mimetypes
from urllib.parse import urljoin, quote
from fastcore.utils import *
from fastcore.meta import delegates
from fastcore.aio import then
from fastcore.apisurface import snake, sanitized_params, mk_sig, mk_doc, OpGroup, mk_groups, full_docs as _full_docs

from fasttransport.errors import APIError
from .spec import OpSpec, SpecParser
from fasttransport.core import AsyncTransport,SyncTransport


# %% ../nbs/04_oapi.ipynb #6b2f1057
def _examples_doc(exs):
    "Render body examples as an `Examples:` doc section, one fenced JSON block per example"
    if not exs: return ''
    return '\n\nExamples:' + ''.join(f"\n- {v.get('summary') or k}:\n```json\n{json.dumps(v['value'], indent=2)}\n```" for k,v in exs.items())

class OpFunc:
    def __init__(self, op_spec, client, base_url, form_encoder=None, defaults=None):
        store_attr()
        self.defaults      = defaults or {}
        self.sparams       = sanitized_params(op_spec.params)
        for o in ('name group path verb route_params query_params body_params request_content_type '
            'file_params docs_url media_url required_params param_docs').split(): setattr(self, o, getattr(op_spec, o))
        self.__name__ = self.name
        self.summary  = op_spec.summary or f"{op_spec.verb} {op_spec.path}"
        self.__signature__ = mk_sig(op_spec, self.sparams, self.defaults)
        self.__doc__       = mk_doc(self, self.__signature__, self.sparams) + _examples_doc(op_spec.body_examples)

    def _repr_markdown_(self): return self.__doc__
    def __repr__(self): return f"{'.'.join(snake(g) for g in listify(self.group))}.{self.name}{self.__signature__}\n{self.docs_url}"

# %% ../nbs/04_oapi.ipynb #6e381df4
@patch
def _bind(self:OpFunc, args, kwargs):
    'Prepare kwargs from args and kwargs; params covered by a call-time default take no positional'
    rsp = {v:k for k,v in self.sparams.items()}
    flds = [o for o in self.__signature__.parameters if o not in kwargs and rsp.get(o,o) not in self.defaults]
    if len(args) > len(flds):
        cov = [o for o in self.__signature__.parameters if rsp.get(o,o) in self.defaults]
        raise TypeError(f"{self.name}: too many positional args; {', '.join(cov)} are covered by client defaults -- pass by keyword to override")
    for a,b in zip(args, flds): kwargs[b] = a
    return kwargs

# %% ../nbs/04_oapi.ipynb #9327d89c
@patch
def _split(self:OpFunc, kwargs):
    "Split kwargs into route/query/body/files + control kwargs."
    stream = kwargs.get("stream", False)
    headers = kwargs.pop("headers_", {})
    # Map sanitized names back to originals
    rsparams = {v:k for k,v in self.sparams.items()}

    route, query, body, files = {}, {}, {}, {}
    for k,v in kwargs.items():
        if v is UNSET: continue
        orig = rsparams.get(k, k)
        if   orig in self.route_params: route[orig] = v
        elif orig in self.file_params:  files[orig] = v
        elif orig in self.query_params: query[orig] = v
        elif orig in self.body_params:  body[orig] = v

    for k,v in self.defaults.items():
        if   k in self.route_params: route.setdefault(k, v)
        elif k in self.query_params: query.setdefault(k, v)

    query.update(kwargs.pop("query_", {}))
    body.update(kwargs.pop("body_", {}))
    if self.verb in ("GET", "DELETE", "HEAD", "OPTIONS") and not body: body = None
    return stream, headers, route, query, body, files

# %% ../nbs/04_oapi.ipynb #7b604f4e
def _path(path, route_params={}):
    "Apply route params to path template."
    if not route_params: return path
    for k,v in route_params.items():
        s = str(v)
        safe = "/" if "/" in s else ""
        path = path.replace("{" + k + "}", quote(s, safe=safe))
        path = path.replace("{+" + k + "}", quote(str(v), safe="/"))
    return re.sub(r"\{\+([^}]+)\}", lambda m: "{" + m.group(1) + "}", path)

# %% ../nbs/04_oapi.ipynb #5f8425a6
def _join_url(base, path):
    "Join base URL and path, ensuring correct slash handling."
    return urljoin(base.rstrip("/") + "/", path.lstrip("/"))

# %% ../nbs/04_oapi.ipynb #ca48c44b
@patch
def _raise_with_context(self:OpFunc, exc:Exception, *, endpoint:str, route:Optional[dict], query:Optional[dict], body:Optional[dict]):
    "Raise APIError with operation context for dynamic op calls."
    provider,model,ep = '','',''
    # TODO: Make APIError generic, users can modify/subclass it include additional info like model,provider etc..
    if isinstance(exc, (httpx2.HTTPStatusError, httpx2.RequestError)):
        raise exc.api_error(provider=provider, model=model) from exc
    raise exc


# %% ../nbs/04_oapi.ipynb #c7c96f87
@patch
@delegates(AsyncTransport.request) # files, raw
async def _request(self:OpFunc, url, *, headers=None, query=None, body=None, route=None, **kwargs):
    "Execute an HTTP request and return decoded response."
    try: return dict2obj(await self.client.request(self.verb, url, headers=headers, params=query, json=body, **kwargs))
    except Exception as e: self._raise_with_context(e, endpoint='', route=route, query=query, body=body)

@patch
@delegates(AsyncTransport.stream) # files, raw
async def _stream(self:OpFunc, url, *, headers=None, query=None, body=None, route=None, **kwargs):
    "Execute an SSE request yielding parsed JSON events."
    try:
        async for ev in self.client.stream(self.verb, url, headers=headers, params=query, json=body, **kwargs): yield dict2obj(ev)
    except Exception as e: self._raise_with_context(e, endpoint='', route=route, query=query, body=body)

# %% ../nbs/04_oapi.ipynb #b91338b1
@patch
def _upload(self:OpFunc, media, media_type, *, headers, query, route, body):
    "Upload `media` through Google's resumable protocol"
    if media is None: raise TypeError(f"{self.name}: `media` is required")
    if isinstance(media, (str, Path)): fname,media = media, Path(media).read_bytes()
    else: fname = body.get('name')
    if hasattr(media, 'read'): media = media.read()
    ctype = media_type or mimetypes.guess_type(fname or '')[0] or 'application/octet-stream'
    url = _path(self.media_url, route_params=route)
    return then(self.client.request('POST', url, headers={**headers, 'X-Upload-Content-Type': ctype}, params={**query, 'uploadType': 'resumable'}, json=body, raw=True),
        ~Self.headers['location'], partial(self.client.request, 'PUT', headers={'Content-Type': ctype}, content=media), dict2obj)

# %% ../nbs/04_oapi.ipynb #0296d943
@patch
def _prep(self:OpFunc, args, kwargs):
    "Resolve call args to (stream, url, headers, query, route, request kwargs)."
    stream, headers, route, query, body, files = self._split(self._bind(args, kwargs))
    url = _join_url(self.base_url, _path(self.path, route_params=route))
    if files: kw = dict(body=None, files=files, data=self.form_encoder(body) or None)
    elif self.request_content_type == "application/x-www-form-urlencoded": kw = dict(body=None, data=self.form_encoder(body))
    else: kw = dict(body=body)
    if kwargs.get("raw_"): kw["raw"] = True
    if stream and kw.get("raw"): raise TypeError("raw_=True can't be combined with stream=True")
    return stream, url, headers, query, route, kw

@patch
async def __call__(self:OpFunc, *args, **kwargs):
    stream, url, headers, query, route, kw = self._prep(args, kwargs)
    if stream: return self._stream(url, headers=headers, query=query, route=route, **kw)
    if not self.media_url: return await self._request(url, headers=headers, query=query, route=route, **kw)
    try: return await self._upload(kwargs.get('media'), kwargs.get('media_type'), headers=headers, query=query, route=route, body=kw['body'])
    except Exception as e: self._raise_with_context(e, endpoint='', route=route, query=query, body=kw['body'])

# %% ../nbs/04_oapi.ipynb #75d6cd54
def op_func(spec, name, group=None):
    "A detached `OpFunc` for spec op `name`: a signature and docs donor, e.g. a `delegates` target for wrappers"
    o = first(o for o in spec.ops if o.name == name and (group is None or o.group == group))
    if o is None: raise ValueError(f'no op named {name!r}' + (f' in group {group!r}' if group else ''))
    return OpFunc(o, None, '')

# %% ../nbs/04_oapi.ipynb #b23f43ae
class SyncOpFunc(OpFunc):
    "`OpFunc` over a `SyncTransport`: calls return results directly, with no `await`."
    def __call__(self, *args, **kwargs):
        stream, url, headers, query, route, kw = self._prep(args, kwargs)
        if stream: raise TypeError("stream=True needs an async client; or wrap the async client with `fastcore.aio.iter_sync`")
        body = kw.pop('body')
        try:
            if self.media_url: return self._upload(kwargs.get('media'), kwargs.get('media_type'), headers=headers, query=query, route=route, body=body)
            return dict2obj(self.client.request(self.verb, url, headers=headers, params=query, json=body, **kw))
        except Exception as e: self._raise_with_context(e, endpoint='', route=route, query=query, body=body)

# %% ../nbs/04_oapi.ipynb #d4ff9dd9
class OpenAPIClient:
    "Client built from OpenAPI operation metadata; async by default, blocking with `sync=True`."
    def __init__(self,
        spec, # A parsed `SpecParser`
        *,
        headers=None, # Base headers for a built transport, e.g. auth
        timeout=60.0, # Timeout for a built transport, in seconds
        form_encoder=None, # Encoder for form-content bodies
        defaults=None, # Param values auto-filled on every call, e.g. `dict(owner='fastai')`
        sync=False, # Build a blocking client? (ignored when `transport` is given: its type decides)
        transport=None, # A `fasttransport` to reuse instead of building one
        base_url=None, # Overrides the spec's base URL, e.g. for a local service instance
    ):
        if transport is None: transport = (SyncTransport if sync else AsyncTransport)(timeout=timeout, base_headers=headers)
        fcls = SyncOpFunc if isinstance(transport, SyncTransport) else OpFunc
        self.transport = transport
        enc = ifnone(form_encoder, noop)
        base_url = ifnone(base_url, spec.base_url)
        self.ops = [fcls(o, self.transport, base_url, enc, defaults) for o in spec.ops]
        self.func_dict = {f"{o.path}:{o.verb.upper()}": o for o in self.ops}
        self.groups = mk_groups(self.ops)
        for k,v in self.groups.items(): setattr(self, k, v)

    def __dir__(self): return object.__dir__(self)

# %% ../nbs/04_oapi.ipynb #a45f810a
@patch
def full_docs(self:OpenAPIClient):
    "Complete markdown API reference: every group and operation."
    return _full_docs(self.groups)

# %% ../nbs/04_oapi.ipynb #b97fc48e
@patch
def __allow__(self:OpenAPIClient): return list(self.groups.values())

