"""Shared async HTTP transport.

Docs: https://AnswerDotAI.github.io/fastspectransport.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_transport.ipynb.

# %% auto #0
__all__ = ['AsyncTransport']

# %% ../nbs/02_transport.ipynb #0dac8355
import httpx, json

from .errors import ProtocolError
from .sse import aiter_sse

# %% ../nbs/02_transport.ipynb #34e9fd7f
class AsyncTransport:
    "Thin async transport wrapper over httpx."
    def __init__(self, *, timeout=60.0, client=None, base_headers=None):
        self._own_client = client is None
        self.client = client or httpx.AsyncClient(timeout=timeout)
        self.base_headers = base_headers or {}

    async def aclose(self):
        if self._own_client: await self.client.aclose()

    def _headers(self, headers=None):
        return {**self.base_headers, **(headers or {})}

    def _request_headers(self, headers=None, *, files=None):
        "Merge headers and drop explicit content-type for multipart uploads."
        h = self._headers(headers)
        if files is not None:
            # Let httpx compute multipart/form-data with boundary.
            for k in list(h):
                if k.lower() == "content-type": h.pop(k, None)
        return h

    @staticmethod
    def _decode(resp):
        "Decode response body using content type."
        if not resp.content: return None
        ctype = (resp.headers.get("content-type") or "").lower()
        if "application/json" in ctype or ctype.endswith("+json"): return resp.json()
        if ctype.startswith("text/") or "application/x-ndjson" in ctype: return resp.text
        return resp.content

    async def request(self, method, url, *, headers=None, params=None, json_data=None, data=None,
                      files=None, raw=False):
        "Execute a request and decode JSON/text/binary response."
        resp = await self.client.request(method, url, headers=self._request_headers(headers, files=files),
            params=params, json=json_data, data=data, files=files)
        try: resp.raise_for_status()
        except httpx.HTTPStatusError as e:
            e.args = (f"{e}\n{resp.text}",)
            raise
        return resp if raw else self._decode(resp)

    async def stream(self, method, url, *, headers=None, params=None,
                            json_data=None, data=None, files=None):
        async with self.client.stream(method, url, headers=self._request_headers(headers, files=files),
            params=params, json=json_data, data=data, files=files) as resp:
            try: resp.raise_for_status()
            except httpx.HTTPStatusError as e:
                try: await resp.aread()
                except Exception: pass
                e.args = (f"{e}\n{resp.text}",)
                raise
            async for event in aiter_sse(resp):
                if not event.data: continue
                if event.data == "[DONE]" or event.event == "message_stop": return
                try: raw = json.loads(event.data)
                except json.JSONDecodeError as e: raise ProtocolError(f"Invalid SSE JSON: {e}") from e
                if isinstance(raw, dict): yield raw
                else: raise ProtocolError(f"Expected SSE JSON object, got {type(raw).__name__}")
