"""Core internal types."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_types.ipynb.

# %% auto #0
__all__ = ['PartType', 'Part', 'Msg', 'ToolCall', 'Usage', 'RequestOptions', 'Completion', 'Delta']

# %% ../nbs/01_types.ipynb #bdde5f36
from dataclasses import dataclass, field

from fastllm.errors import *

# %% ../nbs/01_types.ipynb #e568bade
@dataclass(frozen=True)
class Part:
    "A normalized content part."
    type: str
    text: Optional[str] = None
    data: Optional[Dict] = None

# %% ../nbs/01_types.ipynb #aa3cfc23
PartType = str_enum('PartType', 'text', 'input_image', 'input_audio', 'input_video', 'input_file')

# %% ../nbs/01_types.ipynb #afeb9eef
@dataclass(frozen=True)
class Msg:
    "A normalized message."
    role: str
    content: List[Part]
    data: Optional[Dict] = None

# %% ../nbs/01_types.ipynb #03f5486a
@dataclass(frozen=True)
class ToolCall:
    "Normalized tool call."
    id: str
    name: str
    arguments: Dict = field(default_factory=dict)

# %% ../nbs/01_types.ipynb #5092528f
@dataclass(frozen=True)
class Usage:
    "Normalized usage."
    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0
    raw: Dict[str, Any] = field(default_factory=dict)

# %% ../nbs/01_types.ipynb #1687092f
@dataclass(frozen=True)
class RequestOptions:
    "Request options shared across providers."
    max_tokens: Optional[int] = None
    temperature: Optional[float] = None
    tools: Optional[List[Dict]] = None
    tool_choice: Optional = None
    reasoning_effort: Optional[str] = None
    native: Optional[Dict] = None
    extra_body: Optional[Dict] = None
    extra_headers: Optional[Dict] = None
    extra_query: Optional[Dict] = None

# %% ../nbs/01_types.ipynb #bf1ed159
@dataclass(frozen=True)
class Completion:
    "Normalized completion response."
    model: str
    message: Msg
    finish_reason: Optional[str] = None
    usage: Optional[Usage] = None
    tool_calls: List[ToolCall] = field(default_factory=list)
    provider: Optional[str] = None
    raw: Dict[str, Any] = field(default_factory=dict)

# %% ../nbs/01_types.ipynb #bd624bd6
@dataclass(frozen=True)
class Delta:
    "Normalized streaming delta event."
    text: str = ""
    tool_calls: List[ToolCall] = field(default_factory=list)
    finish_reason: Optional[str] = None
    usage: Optional[Usage] = None
    raw: Dict[str, Any] = field(default_factory=dict)
